version: "3.8"

x-common-variables: &common-variables
  MYSQL_DATABASE: pi_sun
  MYSQL_USER: MYSQL_USER
  MYSQL_PASSWORD: MYSQL_PASSWORD

services:
  mysql_db:
    image: mysql
    restart: always
    cap_add:
      - SYS_NICE
    volumes:
      - "./setup.sql:/docker-entrypoint-initdb.d/setup.sql"
    ports:
      - "3306:3306"
    environment:
      <<: *common-variables
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_HOST: localhost

  nginx:
    depends_on:
      - api_side
      - client_side
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api_side:
    build:
      dockerfile: Dockerfile
      context: "./server-side"
    depends_on:
      - mysql_db
    volumes:
      - /app/node_modules
      - ./server_side:/app
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql_db
    ports:
      - "3001:3001"
    tty: true

  client_side:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: "./client-side"
    volumes:
      - /app/node_modules
      - ./client_side:/app
    ports:
      - "3000:3000"
    tty: true

  # adminer:
  #   image: adminer:latest
  #   restart: unless-stopped
  #   ports:
  #     - 8000:8080
  #   depends_on:
  #     - mysql_db
  #   environment:
  #     ADMINER_DEFAULT_SERVER: mysql_db
